# Generated by Django 2.1.5 on 2019-02-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190206_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.TextField()),
            ],
        ),
    ]
