# Generated by Django 2.1.5 on 2019-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190224_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(choices=[('t1', 't1'), ('t2', 't2'), ('t3', 't3'), ('t4', 't4')], max_length=30),
        ),
    ]
