# Generated by Django 2.1.5 on 2019-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190225_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(choices=[('t1', 't1')], max_length=30),
        ),
    ]
