# Generated by Django 2.1.5 on 2019-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190225_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='main.Product'),
        ),
    ]
