# Generated by Django 2.1.5 on 2019-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190306_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionplan',
            name='steps_executed',
            field=models.IntegerField(null=True),
        ),
    ]
