# Generated by Django 2.1.5 on 2019-03-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_executionplan_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
