# Generated by Django 2.1.5 on 2019-03-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_locationupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationupdate',
            options={'get_latest_by': 'update'},
        ),
    ]
