# Generated by Django 2.1.5 on 2019-03-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190311_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_id', models.CharField(max_length=248)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='executionplan',
            options={'get_latest_by': 'created_at', 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='locationupdate',
            options={'get_latest_by': 'update', 'ordering': ('-update',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('ready', 'ready'), ('delivery', 'delivery'), ('finished', 'finished'), ('aborted', 'aborted')], default='new', max_length=24),
        ),
    ]
