# Generated by Django 2.1.5 on 2019-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190312_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dot_content', models.TextField()),
                ('chef_node', models.CharField(default='chef', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(max_length=30),
        ),
    ]
