# Generated by Django 2.1.5 on 2019-03-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190320_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cafemap',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='synonyms',
            field=models.TextField(help_text='comma separated list of synonyms', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ProductCategory'),
        ),
    ]
