# Generated by Django 2.1.5 on 2019-04-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190401_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': ['updated_at'],
            },
        ),
    ]
